development:
  adapter: postgresql
  database: fashion_startup
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: fashion_startup_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fashion_startup
  pool: 5
  timeout: 5000
